### ISSUE TITLE
Error: Attribute "expanded" has already been defined

### ISSUE THREAD

**Issue by MaSteve** [AAkira/ExpandableLayout#13]
Hi! I'm including your lib to a personal android app and I've found this problem when Android Studio finished to sync the project. I don't know how to fix it, so I open this issue thinking that someone could help me.

Thanks for all your work :)

**Comment by AAkira** [comment]
@MaSteve 

That problem might be because of conflicting `expanded` attributes.
I fixed it on [this commit](https://github.com/AAkira/ExpandableLayout/pull/11/files).
I thought I released v1.2.0 after solved [this issue](https://github.com/AAkira/ExpandableLayout/issues/9).
But I'll release v1.2.0 today.
Could you report here if you can solve it?

**Comment by AAkira** [comment]
@MaSteve 

I release v1.2.0.

**Comment by MaSteve** [comment]
That version solves all my problems.

Thank you very much @AAkira  :)
